#ifndef GAMELOOPCONSTANTS_H_
#define GAMELOOPCONSTANTS_H_

#define WINDOW_POS_X 50
#define WINDOW_POS_Y 50

#define VIEW_WIDTH 960.0f
#define VIEW_HEIGHT 800.0f

#define DESIRED_STATE_UPDATES_PER_SECOND 60
#define DESIRED_STATE_UPDATE_DURATION_MS 10 

#endif /* GAMELOOPCONSTANTS_H_ */
